### ISSUE TITLE
Go Build Error

### ISSUE THREAD

**Issue by sam17** [amrav/sparrow#1]
cannot find package "github.com/pkg/profile" in any of
/Users/dementor/Self/go/src/github.com/amrav/sparrow/vendor/github.com/pkg/profile (vendor tree)
    /usr/local/Cellar/go/1.6.2/libexec/src/github.com/pkg/profile (from $GOROOT)
    /Users/dementor/Self/go/src/github.com/pkg/profile (from $GOPATH)

**Comment by amrav** [comment]
Oops. Fixed by 8799882.

**Comment by imrandurani** [comment]
@sam17 Got same error, how did you solve this problem? Would you please guide?

**Comment by sam17** [comment]
It was fixed by the commit mentioned by @amrav then. If its still present, feel free to reopen the issue.

**Comment by imrandurani** [comment]
well, I am not using sparrow, I am using this package for a different program.
